Update lit dependency and fix tests
Regenerator runtime must be added to karma through a babel plugin.

Otherwise we hit the following error:

```
  An error was thrown in afterAll
    ReferenceError: regeneratorRuntime is not defined
      global.wrappers["/usr/local/google/home/alexlloyd/semantic_locators/javascript/node_modules/@lit/reactive-element/reactive-element.js"]</n</<.value<@/tmp/karma-typescript-bundle--1120053-Dv1ZVczysx56-.js:2533:19
      global.wrappers["/usr/local/google/home/alexlloyd/semantic_locators/javascript/node_modules/@lit/reactive-element/reactive-element.js"]</n<@/tmp/karma-typescript-bundle--1120053-Dv1ZVczysx56-.js:2581:6
      global.wrappers["/usr/local/google/home/alexlloyd/semantic_locators/javascript/node_modules/@lit/reactive-element/reactive-element.js"]<@/tmp/karma-typescript-bundle--1120053-Dv1ZVczysx56-.js:2771:2
      require@node_modules/karma-typescript/dist/client/commonjs.js:17:25
      require/<@node_modules/karma-typescript/dist/client/commonjs.js:18:24
      global.wrappers["/usr/local/google/home/alexlloyd/semantic_locators/javascript/node_modules/lit/index.js"]<@/tmp/karma-typescript-bundle--1120053-Dv1ZVczysx56-.js:2786:8
      require@node_modules/karma-typescript/dist/client/commonjs.js:17:25
      require/<@node_modules/karma-typescript/dist/client/commonjs.js:18:24
      global.wrappers["/usr/local/google/home/alexlloyd/semantic_locators/javascript/test/lib/accessible_name_test.ts"]<@test/lib/accessible_name_test.js:7:38
      require@node_modules/karma-typescript/dist/client/commonjs.js:17:25
      @node_modules/karma-typescript/dist/client/commonjs.js:38:16
      @node_modules/karma-typescript/dist/client/commonjs.js:37:40
      @node_modules/karma-typescript/dist/client/commonjs.js:40:3
```

PiperOrigin-RevId: 434718325